listen_addrs = [
    { local = "[2001:470:ecbf::53]:1443", external = "[2001:470:ecbf::53]:1443" }
]

upstream_addr = "[2001:470:ecbf::666]:53"

state_file = "encrypted-dns.state"

udp_timeout = 10
tcp_timeout = 10

udp_max_active_connections = 1000
tcp_max_active_connections = 100

cache_capacity = 100000
cache_ttl_min = 3600
cache_ttl_max = 86400
cache_ttl_error = 600

client_ttl_holdon = 60
daemonize = false

my_ip = "my.ip"

user = "nobody"
group = "nogroup"

[dnscrypt]
provider_name = "dns.edgy.network"
dnssec = true
no_logs = true
no_filters = false

key_cache_capacity = 10000

[tls]
upstream_addr = "127.0.0.1:4343"

[filtering]

[anonymized_dns]
enabled = true

allowed_ports = [ 443, 553, 853, 1443, 2053, 4343, 4434, 4443, 5353, 5443, 8443, 15353 ]
allow_non_reserved_ports = false

[access_control]
enabled = false
